In [ ]:
# Author: Lennard Alms // Compare to boilerplate to see whats different

In [ ]:
# edit this when working in a local environment
!wget "https://storage.googleapis.com/laubenthal_spatiolab/spatio_merged_data_iss.zip" --no-verbose
!unzip spatio_merged_data_iss.zip
!rm spatio_merged_data_iss.zip

2021-01-29 11:36:12 URL:https://storage.googleapis.com/laubenthal_spatiolab/spatio_merged_data_iss.zip [37282886/37282886] -> "spatio_merged_data_iss.zip" [1]
Archive:  spatio_merged_data_iss.zip
   creating: input/
  inflating: input/.DS_Store         
  inflating: __MACOSX/input/._.DS_Store  
  inflating: input/grid_ML.geojson   
  inflating: __MACOSX/input/._grid_ML.geojson  
  inflating: input/internet_ML.csv   
  inflating: __MACOSX/input/._internet_ML.csv  
  inflating: input/satelite.png      
  inflating: __MACOSX/input/._satelite.png  
  inflating: input/weather.csv       
  inflating: __MACOSX/input/._weather.csv  
  inflating: input/social_pulse_ML.csv  
  inflating: __MACOSX/input/._social_pulse_ML.csv  


In [ ]:
# edit this when working in a local environment
!rm -rf functions
!git clone https://github.com/markuslaubenthal/lab_st.git functions

Cloning into 'functions'...
remote: Enumerating objects: 156, done.
remote: Counting objects: 100% (156/156), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 470 (delta 109), reused 95 (delta 50), pack-reused 314
Receiving objects: 100% (470/470), 187.09 KiB | 1.10 MiB/s, done.
Resolving deltas: 100% (306/306), done.


In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers, activations
from keras import backend as K
from keras.engine.topology import Layer
import tensorflow as tf

In [ ]:
from functions.preprocessing.DataImport import load_and_scale_internet, load_and_scale_satelite, load_and_scale_social, load_and_scale_weather, create_space_invariant
from functions.preprocessing.DataGeneration import generate_dataset, generate_label, getFileHandler, get_datasets_from_file
from functions.postprocessing.ErrorEvaluation import calculate_errors

In [ ]:
f = getFileHandler("training_data.h5")

In [ ]:
internet, internet_origin, internet_min, internet_max = load_and_scale_internet('input/internet_ML.csv', f)

In [ ]:
# Predict no change (Constant traffic assumption)

In [ ]:
x = generate_dataset(internet, [1], 168, f, "x")
y = generate_label(internet, 168, f)
y = y[:].reshape(y.shape[0], 100, 100)

In [ ]:
pred = np.zeros(y.shape)
pred = x[:]
calculate_errors(pred, internet_origin, internet_min, internet_max)

all:  134.34314019416885
test:  141.33611059123365
val:  69.48930740861125


(array([[ 67.07000081,  49.86000068,  37.71000023, ...,  77.68000231,
          79.5700043 ,  80.87000269],
        [ 67.36999933,  50.07000045,  37.84999969, ...,  77.90000315,
          79.89000435,  81.20999596],
        [ 67.68999864,  50.29999989,  37.9899995 , ...,  78.13000035,
          80.22000402,  81.5799998 ],
        ...,
        [207.89000853, 216.59001264, 181.59000109, ..., 103.69000002,
          92.31999786,  91.57000112],
        [141.39997748, 145.35002161, 120.48999526, ...,   0.        ,
           0.        ,   0.        ],
        [135.71998931,  87.83000388,  81.95000375, ...,   0.        ,
           0.        ,   0.        ]]),
 array([[ 49.86,  37.71,  32.08, ...,  79.57,  80.87,  66.74],
        [ 50.07,  37.85,  32.16, ...,  79.89,  81.21,  66.91],
        [ 50.3 ,  37.99,  32.26, ...,  80.22,  81.58,  67.09],
        ...,
        [216.59, 181.59, 134.79, ...,  92.32,  91.57,  68.52],
        [145.35, 120.49,  81.16, ...,   0.  ,   0.  ,   0.  ],
        [

In [ ]:
# Predict using the histoic average (Historical Average)

In [ ]:
x = generate_dataset(internet, [24,24*2,24*3,24*4,24*5,24*6,24*7], 168, f, "x")
y = generate_label(internet, 168, f)
y = y[:].reshape(y.shape[0], 100, 100)

In [ ]:
pred = np.zeros(y.shape)
pred = x[:].mean(axis=3)
calculate_errors(pred, internet_origin, internet_min, internet_max)

all:  231.51487189927252
test:  242.26448980292665
val:  136.66041863206817


(array([[ 53.28485057,  44.92416716,  39.58788412, ...,  81.99456506,
          80.39441529,  74.93854325],
        [ 53.4280187 ,  45.03129173,  39.67213074, ...,  82.27524826,
          80.67327491,  75.19416864],
        [ 53.5854322 ,  45.14396585,  39.75898294, ...,  82.57264092,
          80.96956914,  75.46159968],
        ...,
        [194.3142135 , 160.00823969, 149.91610557, ..., 116.07845115,
         110.01487623, 105.69295642],
        [116.8491283 ,  91.80157348,  83.32975694, ...,   0.        ,
           0.        ,   0.        ],
        [ 83.69489411,  71.40495104,  64.06514419, ...,   0.        ,
           0.        ,   0.        ]]),
 array([[ 49.86,  37.71,  32.08, ...,  79.57,  80.87,  66.74],
        [ 50.07,  37.85,  32.16, ...,  79.89,  81.21,  66.91],
        [ 50.3 ,  37.99,  32.26, ...,  80.22,  81.58,  67.09],
        ...,
        [216.59, 181.59, 134.79, ...,  92.32,  91.57,  68.52],
        [145.35, 120.49,  81.16, ...,   0.  ,   0.  ,   0.  ],
        [

In [ ]:
# Predict using the exponential smoothing (Exponential Smoothing)

In [ ]:
x = generate_dataset(internet, [1,24], 168, f, "x")
y = generate_label(internet, 168, f)
y = y[:].reshape(y.shape[0], 100, 100)

In [ ]:
for alpha in np.linspace(0.7,0.9,11):
  pred = np.zeros(y.shape)
  for t in range(x.shape[0]):
    if t < 23:
      predt = alpha * x[t,:,:,0] + (1 - alpha) * x[t,:,:,1]
      pred[t] = predt
    else:
      predt = alpha * x[t,:,:,0] + (1 - alpha) * pred[t-23]
      pred[t] = predt
  print('_______________________________')
  print('alpha ', alpha)
  calculate_errors(pred, internet_origin, internet_min, internet_max)

_______________________________
alpha  0.7
all:  124.3573989586356
test:  130.54530308513142
val:  68.18283361917977
_______________________________
alpha  0.72
all:  123.77146892650377
test:  129.95770283370538
val:  67.49972632038825
_______________________________
alpha  0.74
all:  123.3736342051697
test:  129.56863014554227
val:  66.9034623068097
_______________________________
alpha  0.76
all:  123.1581776002318
test:  129.3715867963029
val:  66.39724657617724
_______________________________
alpha  0.78
all:  123.12055012461047
test:  129.36128856821693
val:  65.9852574691122
_______________________________
alpha  0.8
all:  123.25734743297707
test:  129.53364831856476
val:  65.67254595915712
_______________________________
alpha  0.8200000000000001
all:  123.56635517771775
test:  129.88583177215529
val:  65.4649536424753
_______________________________
alpha  0.84
all:  124.04652503525854
test:  130.4162415900428
val:  65.36896287348995
_______________________________
alpha  0.86
